site_name: AutoOutreach Documentation
site_description: Documentation for the AutoOutreach system
site_author: AutoOutreach Team
repo_url: https://github.com/yourusername/autooutreach

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Components:
    - Collector: components/collector.md
    - Enricher: components/enricher.md
    - Outreach Bot: components/outreach_bot.md
    - WebUI: components/webui.md
  - Development Guide:
    - Getting Started: dev/getting_started.md
    - Contributing: dev/contributing.md
  - API Reference: api_reference.md

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - toc:
      permalink: true 